spring.application.name=taskmanager
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/taskmanager
spring.data.mongodb.database=taskmanager

# Show MongoDB queries in logs (for debugging)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
